

version: "3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: bcp
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=postgres
    restart: unless-stopped
# APP*****************************************
  springbootapp:
    image: springbootapp:latest
    container_name: springbootapp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres